SELECT APPLICATION_DT AS Data, INTERNAL_ORG_ORIGINAL_RK AS pos, SUM(LOAN_AMOUNT) AS "Сумма выдач" 
FROM db 
GROUP BY APPLICATION_DT, INTERNAL_ORG_ORIGINAL_RK
ORDER BY APPLICATION_DT, INTERNAL_ORG_ORIGINAL_RK 


